environment:
  matrix:
  - julia_version: 0.7
  - julia_version: 1

platform:
  - x86 # 32-bit
  - x64 # 64-bit

branches:
  only:
    - master
    - /release-.*/

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true

install:
  - ps: iex ((new-object net.webclient).DownloadString("https://raw.githubusercontent.com/JuliaCI/Appveyor.jl/version-1/bin/install.ps1"))

build_script:
  - mkdir build
  - cd build
  - set "CMAKE_GEN=Visual Studio 14 2015 Win64"
  - IF %PLATFORM% EQU x86 set "CMAKE_GEN=Visual Studio 14 2015"
  - cmake -G "%CMAKE_GEN%" -DJulia_EXECUTABLE=C:\julia\bin\julia -DCMAKE_INSTALL_PREFIX=..\install\usr ..
  - cmake --build . --config Release --target install

test_script:
  - ctest -V -C Release

after_test:
  - cmake --build . --config Release --target create_zip
  - cd ..
  - copy install\libcxxwrap-julia*.zip .
  - echo %APPVEYOR_JOB_NAME%

artifacts:
  - path: 'libcxxwrap-julia*.zip'

deploy:
  provider: GitHub
  auth_token:
    secure: gT/6HUmJMkLU89J2qu3FZ/OR2Velz//TSA/GJr65M1iNRjTimZLnAk73oRPGtA7d # your encrypted token from GitHub
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
